name: Caches

on:
  push:
    branches: [ "main" ]

jobs:
  job-de-cache:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
      - name: install build
        run: npm install --cache .npm --prefer-offline