name: Pierre
on: push

env:
  JOUR_DE_LA_SEMAINE: Lundi

jobs:
  job_de_salutation:
    runs-on: ubuntu-latest
    env:
      Salutation: Bonjour
    steps:
      - name: "Dire bonjour à Pierre parce que c'est lundi"
        if: ${{ env.JOUR_DE_LA_SEMAINE =! 'Lundi' }}
        run: echo $nimportequoi
        env:
          Prenom: Pierre
          
  job_secret:
    runs-on: ubuntu-latest
    needs: job_de_salutation
    steps:
      - name:  "Secret"
        if: ${{ env.JOUR_DE_LA_SEMAINE == 'Lundi' }}
        run: echo "$TEST2 ${{secrets.test}} $Salutation "
        env:
          TEST2: "<3"

      - name: "encore un test"
        if: ${{ env.JOUR_DE_LA_SEMAINE != 'Mardi' }}
        run: echo "$Travail ${{secrets.MDP}}" 
        env: 
          Travail: "Va travailler Pierre"

