name: Pierre
on: push

env:
  JOUR_DE_LA_SEMAINE: Lundi
#Ne marche pas a part si on enlève le exit 1#
jobs:
  job_de_salutation:
    runs-on: ubuntu-latest
    env:
      Salutation: Bonjour
    steps:
      - name: "Dire bonjour à Pierre parce que c'est lundi"
        if: ${{ env.JOUR_DE_LA_SEMAINE == 'Lundi' }}
        run: exit 1
        env:
          Prenom: Pierre

  #Attend sur job de salutation même s'il ne fonctionne pas, enlever needs pour qu'il s'éxécute directement (job secrets) ou enlever always pour 
  #qu'il ne fonctionne pas s'il le exit 1 est mis#
  job_secret:
    runs-on: ubuntu-latest
    if: always()
    needs: job_de_salutation
    steps:
      - name:  "Secret"
        if: ${{ env.JOUR_DE_LA_SEMAINE == 'Lundi' }}
        run: echo "$TEST2 ${{secrets.test}} $Salutation "
        env:
          TEST2: "<3"

      - name: "encore un test"
        if: ${{ env.JOUR_DE_LA_SEMAINE != 'Mardi' }}
        run: echo "$Travail ${{secrets.MDP}}" 
        env: 
          Travail: "Va travailler Pierre"

      - name: "test encore un"
        if: ${{ env.Salutation == 'Bonjour' }}
        run: echo "$Test ${{secrets.MDP}}"
        env: 
          Test: "salut mec"





