name: Pierre
on: push

env:
  JOUR_DE_LA_SEMAINE: Lundi

jobs:
  job_de_salutation:
    runs-on: ubuntu-latest
    env:
      Salutation: Bonjour
    steps:
      - name: "Dire bonjour à Pierre parce que c'est lundi"
        if: ${{ env.JOUR_DE_LA_SEMAINE == 'Lundi' }}
        run: echo "$Salutation $Prenom. Aujourd'hui, c'est $JOUR_DE_LA_SEMAINE ! ${{secrets.test}}"
        env:
          Prenom: Pierre

      - name:  "Secret"
        if: ${{ env.JOUR_DE_LA_SEMAINE == 'Lundi' }}
        env:
          TEST2: "<3"
        run: echo "$TEST2 $Salutation ${{secrets.test}}"
